export const LOGIN_ACTIONS = {
  START: 'LOGIN_START',
  SUCCESS: 'LOGIN_SUCCESS',
  FAILED: 'LOGIN_FAILED',
};

export const LOGOUT_ACTIONS = {
  START: 'LOGOUT_START',
  SUCCESS: 'LOGOUT_SUCCESS',
  FAILED: 'LOGOUT_FAILED',
};

export const SIGNUP_ACTIONS = {
  START: 'SIGNUP_START',
  SUCCESS: 'SIGNUP_SUCCESS',
  FAILED: 'SIGNUP_FAILED',
};
